cleanup, borrow some code and ideas from nodejs buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
-indent() {
-  sed -u 's/^/       /'
-}
+set -e            # fail fast
+set -o pipefail   # don't ignore exit codes when piping output
 
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
-BIN_DIR=$(cd $(dirname $0); pwd)
+BUILDPACK_DIR=$(cd $(dirname $0); cd ..; pwd)
+
+source $BUILDPACK_DIR/bin/common.sh
+trap cat_cpanm_build_log ERR
 
 CPANMURL='https://raw.github.com/miyagawa/cpanminus/master/cpanm'
 export PERL_CPANM_OPT="--quiet --notest"
-
 CACHED_DIRS="local"
 
 mkdir -p $CACHE_DIR
 cd $BUILD_DIR
 
-export BUILD_DIR CACHE_DIR BIN_DIR
-source $BIN_DIR/steps/hooks/pre_compile $ENV_DIR
+source $BUILDPACK_DIR/bin/steps/hooks/pre_compile $ENV_DIR
 
 for dir in $CACHED_DIRS; do
   cp -R $CACHE_DIR/$dir . &> /dev/null || true
@@ -29,13 +29,13 @@ if [ -e vendor.url ]; then
 fi
 
 if [ ${VENDORURL:+x} ]; then
-  echo "-----> Extracting vendor from $VENDORURL"
+  status "Extracting vendor from $VENDORURL"
   mkdir -p vendor
   curl --silent $VENDORURL | tar -xz -C vendor 2>&1 | indent
 fi
 
 if [ -d vendor ]; then
-  echo "-----> Configuring compile path env for vendor"
+  status "Configuring compile path env for vendor"
   export C_INCLUDE_PATH=`pwd`/vendor/include
   export LIBRARY_PATH=`pwd`/vendor/lib
   export LD_LIBRARY_PATH=`pwd`/vendor/lib
@@ -48,45 +48,45 @@ if [ -e local.url ]; then
 fi
 
 if [ ${LOCALURL:+x} ]; then
-  echo "-----> Extracting prebuilt dependencies from $LOCALURL"
+  status "Extracting prebuilt dependencies from $LOCALURL"
   mkdir -p local
   curl --silent $LOCALURL | tar -xz -C local 2>&1 | indent
 fi
 
-echo "-----> Bootstrapping cpanm and local::lib"
+status "Bootstrapping cpanm and local::lib"
 curl --silent $CPANMURL | perl - --local-lib local App::cpanminus local::lib 2>&1 | indent
 eval $(perl -Ilocal/lib/perl5 -Mlocal::lib=local 2>&1 | indent)
 
-echo "-----> Saving build environment to .buildpack/build/env"
+status "Saving build environment to .buildpack/build/env"
 rm -rf .buildpack/build 2>&1; mkdir -p .buildpack/build 2>&1
 set >.buildpack/build/env
 
 if [ -e local.bundle ]; then
-  echo "-----> Installing local.bundle modules (cpanm)"
+  status "Installing local.bundle modules (cpanm)"
   cat local.bundle | xargs cpanm 2>&1 | indent
   cp /app/.cpanm/build.log .buildpack/build/bundle.log 2>&1 | indent
 fi
 
 if [ -e cpanfile.snapshot ]; then
   if ! command -v carton >/dev/null 2>&1; then
-    echo "-----> Installing carton"
+    status "Installing carton"
     cpanm Carton 2>&1 | indent
   fi
-  echo "-----> Installing dependencies (carton)"
+  status "Installing dependencies (carton)"
   carton install --deployment --cached 2>&1 | indent
   cp /app/.cpanm/build.log .buildpack/build/carton.log 2>&1 | indent
-  echo "-----> Removing vendor/cache"
+  status "Removing vendor/cache"
   rm -rf vendor/cache 2>&1 | indent
 fi
 
-echo "-----> Installing dependencies (cpanm)"
+status "Installing dependencies (cpanm)"
 cpanm --installdeps . 2>&1 | indent
 cp /app/.cpanm/build.log .buildpack/build/cpanm.log 2>&1 | indent
 
-echo "-----> Installing Starman"
+status "Installing Starman"
 cpanm Starman 2>&1 | indent
 
-source $BIN_DIR/steps/hooks/post_compile $ENV_DIR
+source $BUILDPACK_DIR/bin/steps/hooks/post_compile $ENV_DIR
 
 for dir in $CACHED_DIRS; do
   rm -rf $CACHE_DIR/$dir
